---
name: ubuntu-package-changelog
version: git
base: core20
summary: Get Ubuntu package changelogs for different series, pockets and packages
description: |
  Get Ubuntu package changelogs for different series, pockets and packages.

  Example usage:
  ubuntu-package-changelog focal Updates linux-azure --lines 12

grade: stable
confinement: strict

apps:
  ubuntu-package-changelog:
    command: bin/ubuntu-package-changelog
    plugs:
      - network
    environment:
       LC_ALL: C.UTF-8
       PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.8/site-packages/

parts:
  ubuntu-package-changelog:
    plugin: python
    source: .
    build-packages:
      - python3-setuptools-scm
      # for python cryptography
      - libffi-dev
      - rustc
      - cargo
      - libssl-dev
