name: snap

on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Lint with flake8
      run: |
        tox -elint
  snap-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: snapcore/action-build@v1
  snap-test:
    needs: snap-build
